import { Montserrat} from "next/font/google"
import './index.css'
import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'BEKA',
  description: 'Generated by Next.js',
}


const montserrat = Montserrat({ subsets: ["latin"], weight: ["400" , "500" , "600"]})

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={montserrat.className}>
          <Navbar/>
        <main className="max-container">
        {children}
        {/* Footer*/}
        </main>
      </body>
    </html>
  )
}
